# Generated by Django 4.2.17 on 2025-01-13 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=255, null=True)),
                ('entity_id', models.BigIntegerField(null=True)),
                ('action', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.TextField()),
                ('request_headers', models.TextField(null=True)),
                ('request_payload', models.TextField(null=True)),
                ('response_status', models.IntegerField()),
                ('response_payload', models.TextField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('ip_address', models.CharField(max_length=45, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.BigIntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='audit_log_a_entity_915476_idx'), models.Index(fields=['user_id'], name='audit_log_a_user_id_803677_idx'), models.Index(fields=['response_status'], name='audit_log_a_respons_eeb2da_idx'), models.Index(fields=['timestamp'], name='audit_log_a_timesta_1eda2d_idx')],
            },
        ),
    ]
