# Generated by Django 5.1.4 on 2025-01-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadToInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('converted', 'Converted')], default='created', max_length=50)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead_to_invoice.invoice')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_to_invoice.lead')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead_to_invoice.quotation')),
            ],
        ),
    ]
