# Generated by Django 5.1.4 on 2025-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0002_leadtoinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
