# Generated by Django 5.1.4 on 2025-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0003_lead_lead_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
