# Generated by Django 5.1.4 on 2025-01-16 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_to_invoice', '0006_notification_invoice_notification_lead_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='leadtoinvoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead to Invoice', 'verbose_name_plural': 'Leads to Invoices'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='numberingsystemsettings',
            options={'verbose_name': 'Numbering System Setting', 'verbose_name_plural': 'Numbering System Settings'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead_to_invoice.lead'),
        ),
        migrations.AddField(
            model_name='leadtoinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_number',)},
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('lead_number',)},
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('quotation_number',)},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lead', 'status'], name='lead_to_inv_lead_id_0f9be0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='lead_to_inv_email_0b0a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtoinvoice',
            index=models.Index(fields=['lead', 'status'], name='lead_to_inv_lead_id_502650_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='lead_to_inv_status_c63f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='numberingsystemsettings',
            index=models.Index(fields=['type'], name='lead_to_inv_type_687a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['lead', 'status'], name='lead_to_inv_lead_id_5628e4_idx'),
        ),
    ]
