# Generated by Django 4.2.17 on 2025-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_to_invoice", "0008_quotation_original_quotation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="items",
            field=models.JSONField(default=list),
        ),
    ]
