# Generated by Django 4.2.17 on 2025-01-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_to_invoice", "0010_remove_invoice_amount_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_due",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
