# Generated by Django 4.2.17 on 2025-01-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lead_to_invoice", "0011_invoice_amount_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lead_to_invoice.lead"
            ),
        ),
    ]
