# Generated by Django 4.2.17 on 2025-01-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lead_to_invoice", "0012_alter_invoice_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="lead",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead_to_invoice.lead",
            ),
        ),
    ]
